name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Установить зависимости
        run: pip install -r requirements.txt
      - name: Прогнать тесты
        run: pytest src/test_dut_emulator -v